import type {
	BrowserCallOptions,
	BrowserElementManagerInterface,
	BrowserReadingInterface,
} from '@src/core'
import type {
	BrowserDOMElementInterface,
	BrowserDOMViewInterface,
	BrowserDOMViewOptions,
} from './types.js'
import { BrowserError, createBrowserReading, validateBrowserTimeout } from '@src/core'
import { BrowserDOMElementManager } from './elements/BrowserDOMElementManager.js'
import { BROWSER_DOCUMENT_TIMEOUT_MS } from './constants.js'
import { BrowserDOMWait } from './BrowserDOMWait.js'
import {
	collectBrowserRoots,
	isBrowserDocument,
	listenBrowserNavigation,
	readBrowserCapture,
} from './helpers.js'

/**
 * Reads and drives a DOM document from a realm that can reach it, without trusted input.
 *
 * @remarks
 * The view follows the window of the document it was given, so after that window navigates it
 * drives the window's next document. A reading records the view's navigation epoch, and reports
 * stale after the epoch advances. The epoch advances on the Navigation API's `navigatesuccess`
 * where the window has that API, on `popstate` and `hashchange` where it does not, on `pagehide`,
 * and when the window's document changes. A `pushState` in a window without the Navigation API
 * fires none of those events, so a reading there stays current across it. A cross-document
 * navigation also clears every element reference. `destroy()` releases the listeners and every
 * reference, and fails every pending wait with a `BrowserError` coded
 * `BROWSER_DOCUMENT_DESTROYED`; after it, `title()`, `read()`, `wait()`, and the element manager's
 * `outline()`, `find()`, and `wait()` reject with that error, and a second `destroy()` does
 * nothing more. `trusted` is `false`: no action grants user activation, and
 * every event the view's actions dispatch themselves carries `isTrusted` `false`. The `submit`
 * event that `requestSubmit()` fires during a `submit` is generated by the browser and carries
 * `isTrusted` `true`.
 *
 * @example
 * ```ts
 * const view = createBrowserDOMView({ document: frame.contentDocument })
 * const reading = await view.read()
 * reading.text().text
 * ```
 */
export class BrowserDOMView implements BrowserDOMViewInterface {
	readonly #window: Window
	readonly #elements: BrowserDOMElementManager
	readonly #release = new AbortController()
	readonly #navigateHandler = this.#navigate.bind(this)
	#document: Document
	#epoch = 0
	#listeners = new AbortController()

	constructor(options: BrowserDOMViewOptions) {
		const document = options.document
		if (!isBrowserDocument(document) || document.defaultView === null) {
			throw new BrowserError(
				'Browser DOM view requires a document attached to a window',
				'BROWSER_DOCUMENT',
			)
		}
		if (document === globalThis.document && options.own !== true) {
			throw new BrowserError(
				'Browser DOM view drives globalThis.document only with own: true, because an action that navigates the realm it runs in cannot return',
				'BROWSER_DOCUMENT_OWN',
			)
		}
		this.#window = document.defaultView
		this.#document = document
		this.#elements = new BrowserDOMElementManager({
			document: this.#current.bind(this),
			navigation: this.#navigation.bind(this),
			signal: this.#release.signal,
		})
		this.#listen()
	}

	get url(): string {
		return this.#current().URL
	}

	get trusted(): boolean {
		return false
	}

	get elements(): BrowserElementManagerInterface<BrowserDOMElementInterface> {
		return this.#elements
	}

	async title(options?: BrowserCallOptions): Promise<string> {
		this.#release.signal.throwIfAborted()
		options?.signal?.throwIfAborted()
		return this.#current().title
	}

	async read(options?: BrowserCallOptions): Promise<BrowserReadingInterface> {
		this.#release.signal.throwIfAborted()
		options?.signal?.throwIfAborted()
		return createBrowserReading({
			...readBrowserCapture(this.#current().documentElement),
			navigation: this.#navigation.bind(this),
		})
	}

	async wait(text: string, options?: BrowserCallOptions): Promise<void> {
		this.#release.signal.throwIfAborted()
		const start = performance.now()
		const timeout = options?.timeout ?? BROWSER_DOCUMENT_TIMEOUT_MS
		validateBrowserTimeout(timeout)
		const document = this.#current()
		await new BrowserDOMWait({
			roots: collectBrowserRoots.bind(undefined, document),
			check: this.#contains.bind(this, document, text),
			timeout,
			start,
			signal:
				options?.signal === undefined
					? this.#release.signal
					: AbortSignal.any([options.signal, this.#release.signal]),
			subject: 'Browser text wait',
		}).execute()
	}

	destroy(): void {
		this.#release.abort(
			new BrowserError('Browser DOM view was destroyed', 'BROWSER_DOCUMENT_DESTROYED'),
		)
		this.#listeners.abort()
		this.#elements.clear()
	}

	// Returns the window's document, first moving the view onto it after a document change.
	#current(): Document {
		const document = this.#window.document
		if (document !== this.#document && !this.#release.signal.aborted) {
			this.#document = document
			this.#navigate()
			this.#listen()
		}
		return this.#document
	}

	#navigation(): number {
		this.#current()
		return this.#epoch
	}

	#navigate(event?: Event): void {
		this.#epoch += 1
		if (event === undefined || event.type === 'pagehide') this.#elements.clear()
	}

	#contains(document: Document, text: string): true | undefined {
		return (document.body?.innerText ?? '').includes(text) ? true : undefined
	}

	// Subscribes to the navigation events of the window's current document.
	#listen(): void {
		this.#listeners.abort()
		this.#listeners = new AbortController()
		listenBrowserNavigation(this.#window, this.#navigateHandler, this.#listeners.signal)
	}
}
