import type {
	BrowserElementInterface,
	BrowserElementManagerInterface,
	BrowserEpochFunction,
	BrowserToolsetOptions,
	BrowserViewInterface,
	CDPTransportEventMap,
} from '@src/core'
import type { EmitterErrorHandler, EmitterHooks } from '@orkestrel/emitter'

// === Browser document

/**
 * Configures a view that drives one browser document.
 *
 * @remarks
 * - `document` — the document the view reads and acts on; the view follows its window, so a
 *   navigation of that window moves the view to the window's next document
 * - `own` — if `true`, admits the realm's own `globalThis.document`; if `false`, refuses it,
 *   because an action that navigates the realm's own document cannot return. Default: `false`
 */
export interface BrowserDOMViewOptions {
	readonly document: Document
	readonly own?: boolean
}

/**
 * Configures a toolset that drives one browser document.
 *
 * @remarks
 * - `document` and `own` — the driven document and the admission of the realm's own document, as
 *   {@link BrowserDOMViewOptions} describes them
 * - `source` — a source of page tools, such as `@orkestrel/mcp`'s model context bridge; the
 *   toolset adopts its tools and re-adopts on its `change`. Default: no page tools
 * - `tools`, `limit`, `on`, and `error` — as {@link BrowserToolsetOptions} describes them
 */
export interface BrowserDocumentToolsetOptions
	extends
		BrowserDOMViewOptions,
		Pick<BrowserToolsetOptions, 'on' | 'error' | 'tools' | 'source' | 'limit'> {}

/**
 * Carries the accessible-name traversal context.
 *
 * @remarks
 * - `hidden` — if `true`, admits hidden and invisible content, as the hidden-reference exception
 *   does for a hidden element that `aria-labelledby` references; if `false`, omits it.
 *   Default: `false`
 * - `target` — the element whose name is computed; an embedded control that is the target
 *   contributes nothing, and any other embedded control contributes its value
 */
export interface BrowserNameContext {
	readonly hidden?: boolean
	readonly target?: Element
}

/**
 * Provides DOM actions through a stable element reference, without trusted input.
 *
 * @remarks
 * No action grants user activation, and every event an action dispatches itself carries
 * `isTrusted` `false`. `submit` submits the element's form through `requestSubmit()`, passing the
 * element as the submitter when it is a submit button; the `submit` event that call fires is
 * generated by the browser and carries `isTrusted` `true`.
 */
export interface BrowserDOMElementInterface extends BrowserElementInterface {}

/** Provides the document operations of a view that drives a DOM document in its own realm. */
export interface BrowserDOMViewInterface extends BrowserViewInterface {
	readonly elements: BrowserElementManagerInterface<BrowserDOMElementInterface>
	/** Releases the navigation listeners and every element reference. */
	destroy(): void
}

/**
 * Binds a DOM element manager to the view that owns it.
 *
 * @remarks
 * - `document` — returns the document the view drives at the moment of the call
 * - `navigation` — reads the view's navigation epoch, which every reading records
 * - `signal` — the view's lifetime; it aborts when the view is destroyed, every wait and
 *   navigation listener the manager starts ends with it, and after it aborts `outline`, `find`,
 *   and `wait` reject with its reason
 */
export interface BrowserDOMElementManagerInput {
	readonly document: () => Document
	readonly navigation: BrowserEpochFunction
	readonly signal: AbortSignal
}

/**
 * Binds a DOM element to its reference and the manager that minted it.
 *
 * @remarks
 * - `reference` — the reference the manager minted for the element
 * - `description` — returns the role and accessible name the latest capture that encountered
 *   the element recorded; after the manager drops the reference it keeps returning that capture
 * - `node` — a weak reference to the element the reference names, so a removed element can be
 *   collected; an element that no longer dereferences reports `GONE`
 * - `current` — true while the manager still holds the reference; false otherwise
 * - `navigation` — reads the epoch of the element's own document, which every reading records;
 *   it advances when that document or the view's document navigates
 */
export interface BrowserDOMElementInput {
	readonly reference: string
	readonly description: () => Pick<BrowserElementInterface, 'role' | 'name'>
	readonly node: WeakRef<Element>
	readonly current: () => boolean
	readonly navigation: BrowserEpochFunction
}

/**
 * Describes one wait parked on DOM mutations.
 *
 * @remarks
 * - `roots` — returns the documents and shadow roots whose mutations re-run the check; the wait
 *   re-reads it after every mutation batch and every `load` in an observed root, observing the
 *   roots that appeared and releasing the ones that departed, and a `pagehide` in the first
 *   root's window fails the wait
 * - `check` — returns the value the wait settles on, or `undefined` to keep waiting
 * - `timeout` — ms from `start` before the wait fails
 * - `start` — the `now()` reading the deadline counts from, taken when the calling method was
 *   entered
 * - `now` — reads the clock every remaining-budget calculation uses, the deadline timer's delay
 *   included; it shares its time origin with `start`. Default: `performance.now()`
 * - `signal` — aborts the wait with the signal's reason
 * - `subject` — names the wait in its timeout message
 */
export interface BrowserMutationWait<T> {
	readonly roots: () => readonly Node[]
	readonly check: () => T | undefined
	readonly timeout: number
	readonly start: number
	readonly now?: () => number
	readonly signal?: AbortSignal | undefined
	readonly subject: string
}

/** Settles one wait parked on DOM mutations. */
export interface BrowserDOMWaitInterface<T> {
	/** The roots the wait observes at this moment; empty before it parks and after it settles. */
	readonly roots: readonly Node[]
	/**
	 * Resolves the first value the check returns other than `undefined`, then releases every
	 * observer, the deadline timer, and every listener.
	 */
	execute(): Promise<T>
}

// === Browser socket transport

/**
 * Configures a CDP transport over the browser's `WebSocket`.
 *
 * @remarks
 * - `url` — the CDP WebSocket debugger URL, with a `ws:` or `wss:` scheme
 * - `timeout` — ms before an opening handshake fails. Default: `BROWSER_DEFAULT_TIMEOUT_MS`
 *
 * The driven Chromium must be started with `--remote-allow-origins` naming the caller's origin;
 * otherwise it refuses the handshake and `start` rejects.
 */
export interface SocketCDPTransportOptions {
	readonly on?: EmitterHooks<CDPTransportEventMap>
	readonly error?: EmitterErrorHandler
	readonly url: string
	readonly timeout?: number
}
